
title: Computer Science Portfolio
email: lukas.mueller@snhu.edu
logo: /images/bd_vis.jpg
description: >- # this means to ignore newlines until "baseurl:"
  This site is dedicated to displaying noteworthy work done in the field of computer science.
show_downloads: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lumutek.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lumutek
# Build settings
theme: minima
#remote_theme: jekyll-theme-chirpy
#remote_theme: mmistakes/jekyll-theme-basically-basic 
#remote_theme: jekyl-theme-hacker
#remote_theme: jekyl-theme-time-machine
remote_theme: jekyl-theme-midnight
#remote_theme: pages-themes/hacker
plugins:
  - jekyll-feed
  - jekyll-remote-theme
